CREATE TABLE IF NOT EXISTS worker
(
    ID       INT           NOT NULL AUTO_INCREMENT,
    NAME     VARCHAR(1000) NOT NULL CHECK ( CHAR_LENGTH(NAME) >= ? AND CHAR_LENGTH(NAME) <= ? ),
    BIRTHDAY DATE          NOT NULL CHECK ( BIRTHDAY > ? ),
    LEVEL    VARCHAR(7)    NOT NULL CHECK ( LEVEL IN (?, ?, ?, ?) ),
    SALARY   INT CHECK ( SALARY >= ? AND SALARY <= ? ),
    PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS client
(
    ID   INT           NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(1000) NOT NULL CHECK ( CHAR_LENGTH(NAME) >= 2 AND CHAR_LENGTH(NAME) <= 1000 ),
    PRIMARY KEY (ID)
    );
CREATE TABLE IF NOT EXISTS project
(
    ID          INT NOT NULL AUTO_INCREMENT,
    CLIENT_ID   INT,
    START_DATE  DATE,
    FINISH_DATE DATE,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENT_ID) REFERENCES client (ID)
    );
CREATE TABLE IF NOT EXISTS project_worker
(
    PROJECT_ID INT NOT NULL,
    WORKER_ID  INT NOT NULL,
    PRIMARY KEY (PROJECT_ID, WORKER_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES project (ID),
    FOREIGN KEY (WORKER_ID) REFERENCES worker (ID)
    );


